"""Initial migration

Revision ID: 9f55c0f51624
Revises: 
Create Date: 2024-08-25 15:03:32.755701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f55c0f51624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('text_to_speech_use', sa.String(length=100), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=True),
    sa.Column('visibility', sa.String(length=100), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tts', sa.String(length=64), nullable=True),
    sa.Column('avatar_id', sa.String(length=100), nullable=True),
    sa.Column('background_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('server_message_unicode', sa.Text(), nullable=True),
    sa.Column('feedback', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('client_message', sa.String(length=1000), nullable=True),
    sa.Column('server_message', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('character_id', sa.String(length=100), nullable=True),
    sa.Column('tools', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('llm_config', sa.JSON(), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_table('memory',
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('source_session_id', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('memory')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('feedbacks')
    op.drop_table('characters')
    # ### end Alembic commands ###
